name: Framework CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  ci:
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, macos-latest ]
        php-versions: [ '7.4' ]
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ${{ matrix.operating-system }}

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ast, iconv, json, mbstring, pdo, tokenizer
          coverage: xdebug #optional
          ini-values: zend.assertions=1,assert.exception=1
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: make install

      - name: Build the project
        run: make build

      - name: Coverage report
        if: ${{ matrix.operating-system == 'ubuntu-latest' && matrix.php-versions == '7.4' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make coverage
